<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>PolyCraft</RootNamespace>
    <AssemblyName>PolyCraft</AssemblyName>
    <Nullable>disable</Nullable>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
